version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - Dependencies

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - Dependencies
      - JavaScript
    ignore:
      # styled components is not yet compatible.
      - dependency-name: stylis-plugin-rtl
        versions:
          - '>= 2'

      # Package is ESM-only, can't use it just yet.
      - dependency-name: markdown-table
        versions:
          - '>= 3'

      # Needs manual upgrade.
      - dependency-name: husky
        versions:
          - '>= 6'

  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - Dependencies
      - PHP
